language: rust

sudo: required

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

after_success: |
  rustup component add llvm-tools-preview &&
  cargo install cargo-llvm-cov &&
  cargo llvm-cov --all-features --lib --workspace --lcov --output-path lcov.info &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"